* Getting Started

** Contents of this tutorial
- Introduction
   - Where to use Vaadin
   - Where not to use Vaadin
   - The book of Vaadin
   - Documentation
 - Setup Vaadin and Maven
   - Setting up Maven
   - Creating your first project
   - Running it on server
 - Other servers
   - Apache Tomcat
   - JBoss
   - Jetty

** Introduction
    
Vaadin is a web development framework used to develop complex web applications. With Vaadin you can develop web applications with Java (or any JVM based language). You don't have to learn any complicated web technology to get going. Developing apps in Vaadin is like developing apps in SWT. Vaadin will take care of everything from converting your code to server side code and creating the UI components when required.

*** Where to (and not to) use Vaadin

Vaadin is suitable for applications which have lot of forms and data content and have lot of user interaction. Apps having a very complicated structure and rich layout. With Vaadin these user interactions and navigations can be simplified as you are not using HTML anymore.

If your app has very few pages or very less user interaction or your app has lot of static pages, then Vaadin is not for you. Some other framework will be better to use.

*** Documentation and help

Help material can be found at the [[http://www.vaadin.com][official website]] of Vaadin. There is the [[http://www.vaadin.com/book][Book of Vaadin]] which has all the material requred to develop simple Vaadin applications. Why I came up with this blog, you will understand when you read the book. [[http://www.demo.vaadin.com/sampler][Vaadin Sampler]] has almost all the Vaadin components with their basic usage. These components can sometimes help you decide between components and understand the use of components.
